INSERT INTO genre(name) values ('80''s rock');
INSERT INTO genre(name) values ('80''s disco');
INSERT INTO genre(name) values ('disco');
INSERT INTO genre(name) values ('punk');
INSERT INTO genre(name) values ('indie rock');
INSERT INTO genre(name) values ('blues');
INSERT INTO genre(name) values ('rock');
INSERT INTO genre(name) values ('hard rock');
INSERT INTO genre(name) values ('hardcore punk');
INSERT INTO genre(name) values ('progressive rock');
INSERT INTO genre(name) values ('progressive metal');
INSERT INTO genre(name) values ('grunge');
INSERT INTO genre(name) values ('classical');
INSERT INTO genre(name) values ('country');
INSERT INTO genre(name) values ('bluegrass');
INSERT INTO genre(name) values ('hip-hop');
INSERT INTO genre(name) values ('soul');
INSERT INTO genre(name) values ('jazz');
INSERT INTO genre(name) values ('big band jazz');
INSERT INTO genre(name) values ('fusion');
INSERT INTO genre(name) values ('gypsy jazz');
INSERT INTO genre(name) values ('reggie');
INSERT INTO genre(name) values ('pop');
INSERT INTO genre(name) values ('funk');
INSERT INTO genre(name) values ('80''s glam rock');
INSERT INTO genre(name) values ('progressive metal');
INSERT INTO genre(name) values ('death metal');
INSERT INTO genre(name) values ('instrumental progressive rock');
INSERT INTO genre(name) values ('instrumental progressive metal');
INSERT INTO genre(name) values ('speed metal');
INSERT INTO genre(name) values ('post rock');
INSERT INTO genre(name) values ('trash metal');
INSERT INTO genre(name) values ('indie');
INSERT INTO genre(name) values ('synth pop');
INSERT INTO genre(name) values ('rap');
INSERT INTO genre(name) values ('hardcore');
INSERT INTO genre(name) values ('country pop');